server:
  host:
    ip: 0.0.0.0
    port: 8000
  credential:
    admin:
      id: admin
      pw: demo
      encrypt: aes128
  auth:
    token: jwt
    expires: 3600
    anonymous: false
  debug: false
