debug = true

[server]

  [server.host]
  ip = "0.0.0.0"
  port = 8000.0

[credential]

  [credential.admin]
  id = "admin"
  pw = "demo"
  encrypt = "aes128"

[auth]
token = "jwt"
expires = 3600.0
anonymous = false
