name: Go

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: setup
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: checkout
      uses: actions/checkout@v2

    - name: pre-build
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: test
      run: go test ./...
